<a href="https://colab.research.google.com/github/anovaes2002/IFES/blob/main/aula_IA_14_10_21_ALEXNOVAES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
uploaded = files.upload()


Saving iris.data to iris.data


In [4]:
import numpy as np
import pandas as pd
import seaborn as nsn
import matplotlib.pyplot as plt
import google

In [5]:
base=pd.read_csv('iris.data')  

In [6]:
base.head

<bound method NDFrame.head of      5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]>

In [7]:
entradas = base.iloc[:,0:4].values
saidas = base.iloc[:,4].values

In [8]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [9]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
saidas = labelencoder.fit_transform(saidas)
print(saidas)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [10]:
from keras.utils import np_utils
saidas_dummy = np_utils.to_categorical(saidas)
print(saidas_dummy)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [11]:
from sklearn.model_selection import train_test_split

etreino, eteste, streino, steste = train_test_split(entradas, saidas_dummy, test_size = 0.25)


In [12]:
print(etreino)

[[5.6 3.  4.5 1.5]
 [6.3 3.3 4.7 1.6]
 [6.2 2.8 4.8 1.8]
 [4.7 3.2 1.3 0.2]
 [5.2 2.7 3.9 1.4]
 [5.9 3.  5.1 1.8]
 [7.2 3.2 6.  1.8]
 [6.9 3.2 5.7 2.3]
 [6.9 3.1 5.1 2.3]
 [6.  3.4 4.5 1.6]
 [4.6 3.2 1.4 0.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  3.6 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.  1.6 0.2]
 [6.9 3.1 4.9 1.5]
 [6.4 3.2 5.3 2.3]
 [4.5 2.3 1.3 0.3]
 [5.6 3.  4.1 1.3]
 [6.4 3.2 4.5 1.5]
 [4.4 2.9 1.4 0.2]
 [5.7 2.9 4.2 1.3]
 [5.9 3.  4.2 1.5]
 [5.  3.5 1.6 0.6]
 [6.5 3.  5.8 2.2]
 [6.2 2.9 4.3 1.3]
 [6.1 2.9 4.7 1.4]
 [7.7 2.6 6.9 2.3]
 [6.3 3.3 6.  2.5]
 [6.5 3.  5.5 1.8]
 [6.4 2.7 5.3 1.9]
 [5.1 3.3 1.7 0.5]
 [6.7 3.1 4.4 1.4]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [7.6 3.  6.6 2.1]
 [5.6 2.7 4.2 1.3]
 [4.6 3.4 1.4 0.3]
 [6.3 2.5 4.9 1.5]
 [5.5 2.4 3.8 1.1]
 [5.6 2.5 3.9 1.1]
 [6.2 2.2 4.5 1.5]
 [4.9 3.  1.4 0.2]
 [6.7 3.3 5.7 2.1]
 [5.8 2.7 3.9 1.2]
 [6.7 3.1 5.6 2.4]
 [4.9 3.1 1.5 0.1]
 [7.2 3.6 6.1 2.5]
 [6.4 2.8 5.6 2.2]
 [6.6 2.9 4.6 1.3]
 [5.7 4.4 1.

In [13]:
from keras.models import Sequential
from keras.layers import Dense

classificador = Sequential()

classificador.add(Dense(50, activation='relu', input_dim = 4))
classificador.add(Dense(50, activation='relu'))
classificador.add(Dense(3, activation='softmax'))
classificador.summary()



Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                250       
_________________________________________________________________
dense_1 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 153       
Total params: 2,953
Trainable params: 2,953
Non-trainable params: 0
_________________________________________________________________


In [14]:
classificador.compile(optimizer= 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [15]:
classificador.fit(etreino, streino, batch_size=10, epochs=100, validation_split=0.2)

Epoch 1/100
9/9 [==============================] - 1s 40ms/step - loss: 1.1211 - accuracy: 0.4659 - val_loss: 0.9064 - val_accuracy: 0.5652
Epoch 2/100
9/9 [==============================] - 0s 4ms/step - loss: 0.8664 - accuracy: 0.5341 - val_loss: 0.8730 - val_accuracy: 0.5652
Epoch 3/100
9/9 [==============================] - 0s 4ms/step - loss: 0.7929 - accuracy: 0.6023 - val_loss: 0.7585 - val_accuracy: 0.7391
Epoch 4/100
9/9 [==============================] - 0s 4ms/step - loss: 0.7252 - accuracy: 0.6477 - val_loss: 0.6589 - val_accuracy: 0.7391
Epoch 5/100
9/9 [==============================] - 0s 4ms/step - loss: 0.6690 - accuracy: 0.6477 - val_loss: 0.5898 - val_accuracy: 0.7391
Epoch 6/100
9/9 [==============================] - 0s 4ms/step - loss: 0.6241 - accuracy: 0.6477 - val_loss: 0.5496 - val_accuracy: 0.7391
Epoch 7/100
9/9 [==============================] - 0s 4ms/step - loss: 0.5833 - accuracy: 0.6477 - val_loss: 0.5062 - val_accuracy: 0.7826
Epoch 8/100
9/9 [=========

In [16]:
score = classificador.evaluate(eteste, steste, verbose=1)
print('Test score', score[0])
print('Test accuracy', score[1])


2/2 [==============================] - 0s 5ms/step - loss: 0.0532 - accuracy: 0.9737
Test score 0.053213972598314285
Test accuracy 0.9736841917037964


In [17]:
import numpy as np
from sklearn.metrics import confusion_matrix

previsoes = classificador.predict(eteste)

steste2 = [np.argmax(t) for t in steste]
previsoes2 = [np.argmax(t) for t in previsoes]
matrizconfusao = confusion_matrix(previsoes2, steste2)

print(matrizconfusao)

[[18  0  0]
 [ 0 12  0]
 [ 0  1  7]]


In [18]:
print(steste2)

[1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 2, 2]
